# Generated by Django 4.2.4 on 2023-08-18 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.CharField(max_length=100, null=True, verbose_name='Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Nro')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creado')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('actividad_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.actividades', verbose_name='Actividad')),
                ('asginado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas_a', to=settings.AUTH_USER_MODEL, verbose_name='Asignado')),
                ('asignador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actividad_asignado_por', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
            ],
        ),
    ]
