# Generated by Django 4.2.4 on 2023-08-18 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_estado_rename_actividades_actividadtipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.estado', verbose_name='Estado'),
        ),
    ]
