# Generated by Django 4.2.4 on 2023-08-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='EstadoStandar',
        ),
    ]
