# Generated by Django 4.2.4 on 2023-08-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_rename_estado_estadostandar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porcentaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField(blank=True, choices=[[0, '0'], [1, '10'], [2, '20'], [3, '30'], [4, '40'], [5, '50'], [6, '60'], [7, '70'], [8, '80'], [9, '90'], [10, '100']], null=True, verbose_name='Porcentaje')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='porcentaje',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actividades.porcentaje', verbose_name='Porcentaje'),
        ),
    ]
