# Generated by Django 4.2.4 on 2023-08-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_porcentaje_actividad_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='porcentaje',
            field=models.IntegerField(choices=[[0, '0'], [1, '10'], [2, '20'], [3, '30'], [4, '40'], [5, '50'], [6, '60'], [7, '70'], [8, '80'], [9, '90'], [10, '100']], default=0, verbose_name='Porcentaje'),
        ),
        migrations.DeleteModel(
            name='Porcentaje',
        ),
    ]
